name: example
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  flex_color_scheme: ^8.4.0
  lpinyin: ^2.0.3
  string_validator: ^1.2.0
  contact_list_view:
    path: ../
  easy_refresh: ^3.5.1
  material_ui: any
  cupertino_ui: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
